### ISSUE TITLE
박스 이미지에서 박스의 선분 길이 검출

### ISSUE THREAD

**Issue by jagaldol** [Box-size/box.size-algorithm#5]
## Description

crop된 박스 이미지에서 박스의 선을 검출해야 됩니다

## Tasks

- [ ] 박스이미지에서 선 검출
- [ ] 찾은 선으로 선분 길이 계산

**Comment by jagaldol** [comment]
여기다가 [허프 라인 변형](http://www.gisdeveloper.co.kr/?p=6714)을 적용해서 선분의 최대길이를 지정하면 좀 정돈이 될까요?

나중에 해보면 좋을 것 같아요

## 기타 참고 사항 링크

[canny edge의 파라미터](https://engineer-mole.tistory.com/243)

[도로 차선 인식 프로그램](https://codingwell.tistory.com/60)

**Comment by ssigner** [comment]
좋은 아이디어인거 같습니다. 저도 OpenCV 관련해서 더 찾아볼게요.
